경로: src/main/resources/application.yml 

server:
  port: 8080

spring:
  application:
    name: com

  datasource:
    url: jdbc:postgresql://localhost:5432/checkmate
    username: 각자의_유저네임
    password: 각자의_비밀번호
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
      ssl:
        enabled: false

cloud:
  aws:
    region:
      static: us-east-1
    s3:
      bucket: checkmate-bucket-g  # 본인 lab bucket 만들고 이름 넣기 
    credentials:
      access-key: 본인_ASIA키        # Learner Lab AWS Details에서 복사
      secret-key: 본인_시크릿키      # Learner Lab AWS Details에서 복사
      session-token: 본인_세션토큰   

jwt:
  secret: Wbe9CZ34cSolL2eWLFRwHOTnxyt8cJ3bMevTaVZtb+w=
  access-token-expiration: 1800000
  refresh-token-expiration: 604800000

swagger:
  server:
    url: http://localhost:8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
